name: winpeer
version: 1.0.10
summary: Flutter Demo winpeer Application
description: A demo of winpeer Application using Flutter
confinement: strict
base: core18
grade: stable
icon: snap/gui/icon.png


apps:
   flutter-share-screen:
     command: winpeer
     extensions: [flutter-master]
     plugs:
       - network
       - desktop

parts:
  flutter-share-screen:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application